services:
  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
      - app4

  app1:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app_php1
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  app2:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app_php2
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  app3:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app_php3
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  app4:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app_php4
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - app_db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    container_name: app_redis
    ports:
      - "6379:6379"

volumes:
  app_db_data:
